name: Jar

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # java: [8, 11, 17, 21]

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Checkout
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY.git repo

      - name: Build
        run: |
          cd repo
          ./gradlew jar sourcesJar javadocJar

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: repo/lib/build/libs/*.jar
